/**
 * Vendor the webfonts locally instead of hotlinking Google Fonts.
 *
 * Why: one less third-party request on every page load, no dependency on
 * fonts.googleapis.com staying up, and no visitor IPs handed to Google.
 *
 * Run with `npm run fonts`. Only needs re-running if the families or weights
 * change — the downloaded .woff2 files are committed.
 */
import { writeFile, mkdir } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(root, "assets", "fonts");

// Chrome UA so Google serves woff2 (variable) rather than legacy formats.
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0 Safari/537.36";

const API =
  "https://fonts.googleapis.com/css2" +
  "?family=Fraunces:ital,opsz,wght@0,9..144,300..600;1,9..144,300..600" +
  "&family=Inter:wght@400..600" +
  "&display=swap";

// Latin covers this site; the other subsets are dead weight.
const SUBSETS = new Set(["latin", "latin-ext"]);

await mkdir(fontsDir, { recursive: true });

const css = await fetch(API, { headers: { "User-Agent": UA } }).then((r) => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
  return r.text();
});

const faces = [];

for (const chunk of css.split("/*").slice(1)) {
  const subset = chunk.slice(0, chunk.indexOf("*/")).trim();
  if (!SUBSETS.has(subset)) continue;

  const body = chunk.slice(chunk.indexOf("*/") + 2);
  const url = body.match(/https:\/\/fonts\.gstatic\.com[^)]*/)?.[0];
  if (!url) continue;

  const family = body.match(/font-family:\s*['"]([^'"]+)/)[1];
  const italic = /font-style:\s*italic/.test(body);
  const slug = family.toLowerCase().replace(/\s+/g, "-");
  const file = `${slug}${italic ? "-italic" : ""}-${subset}.woff2`;

  const bytes = Buffer.from(
    await fetch(url, { headers: { "User-Agent": UA } }).then((r) => r.arrayBuffer())
  );
  await writeFile(join(fontsDir, file), bytes);

  faces.push({
    file,
    label: `${family}${italic ? " italic" : ""} — ${subset}`,
    css: body.replace(/https:\/\/fonts\.gstatic\.com[^)]*/, `/assets/fonts/${file}`).trim(),
    size: bytes.length,
  });

  console.log(`${(bytes.length / 1024).toFixed(0).padStart(4)} KB  ${file}`);
}

if (!faces.length) throw new Error("No matching @font-face blocks found — did the API change?");

const out =
  "/* Generated by `npm run fonts` — do not edit by hand.\n" +
  "   Fraunces and Inter, SIL Open Font License 1.1. */\n\n" +
  faces.map((f) => `/* ${f.label} */\n${f.css}`).join("\n\n") +
  "\n";

await writeFile(join(root, "src", "fonts.css"), out);
console.log(`\nWrote src/fonts.css — ${faces.length} faces, ${(faces.reduce((n, f) => n + f.size, 0) / 1024).toFixed(0)} KB total`);
